#!/bin/bash
# chmod +x ./ejercicio2

# Build if build is not available
make all

# Save parameter files to file containing files :) so we can run malva with its makefile
printf "$1\n$2\n" > files.txt

# Run malva with right parameters files
make SEQ
